# Generated by Django 3.0.5 on 2020-04-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_listener'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listener',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='listener',
            field=models.TextField(default='some string'),
        ),
    ]
